version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes: 
            - .:/app/
        links:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/
    db:
        image: postgres
        restart: always
        ports:
            - "5455:5432"
        volumes:
            - ./data.sql:/docker-entrypoint-initdb.d/data.sql 

        environment:
            POSTGRES_USER: UseR
            POSTGRES_PASSWORD: PassworD
            POSTGRES_DB: db_name